# Generated by Django 5.2.17 on 2026-08-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibility',
            name='form_schema',
            field=models.JSONField(blank=True, default=[], max_length=200),
            preserve_default=False,
        ),
    ]
