# Generated by Django 5.2.17 on 2026-08-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_responsibility_form_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='date',
        ),
    ]
