# Generated by Django 5.2.17 on 2026-09-08 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dataentry_action_date_dataentry_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsibility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_state', to='core.responsibility')),
            ],
        ),
    ]
