# Generated by Django 5.2.17 on 2026-09-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_responsibility_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibility',
            name='secret_code',
        ),
    ]
