# Generated by Django 5.2.17 on 2026-09-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='access_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
